security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'plaintext'
    providers:
        custom_ldap_user_provider:
            id: App\Security\UserProvider\LdapUserProvider
        ldap_user_provider:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: '%env(LDAP_BASE_DN)%'
                search_dn: '%env(SEARCH_DN)%'
                search_password: '%env(LDAP_ADMIN_PASSWORD)%'
                default_roles: ['ROLE_COLLAB']
                uid_key: cn
                extra_fields: [ 'displayName' ]
                password_attribute: userPassword
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: custom_ldap_user_provider
            form_login_ldap:
                service: Symfony\Component\Ldap\Ldap
                login_path: app.security.login
                check_path: app.security.login
                enable_csrf: true
                dn_string: '%env(DN_STRING)%'
                default_target_path: app_profile
            logout:
                path: /logout
                target: app.security.login

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
