controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


homepage:
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    path: /
    defaults:
        template: static/homepage.html.twig